# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0d957a4f713398310c33cc9b5b74f1fea5b1aeffaba930f9dc6d527e2c6fb56aa0145520724e365743ac1bcc128ee04b0923104bb44b81bfefb5e00e398eeae

test:
  secret_key_base: 7865b32e8521db96c61bea348175af41c97f1841c56b0ec444dae5b11030075beeff4b85898bc2cba87c7b0f14b0fa35d35ca4335bd26b502650975820b010aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
